import Head from 'next/head';
import { Inter } from '@next/font/google';
import App from '../src/modules/App';
import UserContextProvider from '../src/context/UserContext/UserContext';
import { RoomContextProvider } from '../src/context/RoomContext/RoomContext';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mind Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserContextProvider>
        <RoomContextProvider>
          <App />
        </RoomContextProvider>
      </UserContextProvider>
    </>
  );
}
